### ISSUE TITLE
where-do-i-belong

### ISSUE THREAD

**Issue by andreasonny83** [thomasvaeth/freecodecamp#1]
where-do-i-belong is wrong according to the Freecodecamp description.
The following tests are failing:
getIndexToIns([10, 20, 30, 40, 50], 35) should return 3.
getIndexToIns([10, 20, 30, 40, 50], 30) should return 2.
getIndexToIns([40, 60], 50) should return 1.
getIndexToIns([3, 10, 5], 3) should return 0.
getIndexToIns([5, 3, 20, 3], 5) should return 2.
getIndexToIns([2, 20, 10], 19) should return 2.
getIndexToIns([2, 5, 10], 15) should return 3.

Consider the following solution instead:

```
function getIndexToIns(arr, value) {
  var pos = 0;
  var i = 0;
  var sortedArr = arr.sort(function(a, b) {
    return a - b;
  });

  for (i = 0; i < sortedArr.length; i++) {
    if (sortedArr[0] >= value) {
      pos = 0;
      break;
    }

    if (value <= sortedArr[i + 1]) {
      pos = i + 1;
      break;
    }

    if (i + 1 === sortedArr.length) {
      pos = sortedArr.length;
      break;
    }
  }

  return pos;
}
```

**Comment by thomasvaeth** [comment]
A lot of these challenges have been updated on FCC. I've gone back and changed a few of them. Just changed this one. https://github.com/thomasvaeth/freecodecamp/blob/master/basic-algorithm-scripting/where-do-i-belong.js Let me know if you find anymore.
